leaves_recognition/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^', include('recognition.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recognition/urls.py
from django.conf.urls import url
from . import views

app_name = 'recognition'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<id>\d+)/$', views.recognition, name='recognition'),
    url(r'^all_pictures/$', views.ShowAll.as_view(), name='all_pic'),
    url(r'^account/$', views.PersonalAcc.as_view(), name='personal_acc'),
    url(r'^search_result/?$', views.SearchList.as_view(), name='search'),
    url(r'^all_trees/$', views.show_trees, name='trees'),
    url(r'^all_trees/(?P<id>\d+)/$', views.the_tree, name='the_tree'),
]

recognition/models.py
from django.db import models
from django.conf import settings


class Tree(models.Model):
    title = models.CharField(max_length=250, unique=True)
    description = models.TextField()
    image = models.ImageField(upload_to='trees')

    def __str__(self):
        return str(self.title).upper()


class Recognition(models.Model):
    tree = models.ForeignKey(Tree, on_delete=models.CASCADE, null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True)
    image = models.ImageField(upload_to='recognitions')
    result = models.CharField(max_length=250, null=Tree)
    created_at = models.DateTimeField(auto_now_add=True, auto_now=False)
    modified_at = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return str(self.id) + ' ' + str(self.tree).upper() + ' ' + str(self.created_at)

recognition/forms.py
from django import forms


class RecognitionImageForm(forms.Form):
    image = forms.FileField(label='Choose')

    def clean_image(self):
        image_file = self.cleaned_data.get('image')
        if not image_file.name.endswith(".jpg"):
            raise forms.ValidationError("Only .jpg image accepted")
        return image_file

recognition/views.py
from django.views import generic
from .forms import RecognitionImageForm
from .models import Recognition, Tree
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.core.urlresolvers import reverse
from recognition.what_leaf_is import label_image
from functools import reduce
from django.db.models import Q, Count
import operator


class IndexView(generic.FormView):
    template_name = 'recognition/index.html'
    form_class = RecognitionImageForm

    def form_valid(self, form):
        recognition_image = Recognition(image=self.get_form_kwargs().get('files')['image'])
        recognition_image.save()
        result = label_image.recognition(recognition_image.image.path)
        print(result)
        recognition_image.tree = Tree.objects.get(title=result[0])
        recognition_image.result = ', '.join(str(i) for i in result)
        if self.request.user.is_authenticated():
            recognition_image.user = self.request.user
        else:
            recognition_image.user = None
        recognition_image.save()
        self.id = recognition_image.id
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('recognition:recognition', kwargs={'id': self.id})


def recognition(request, id=None):
    instance = get_object_or_404(Recognition, id=id)
    result = instance.result.split(', ')
    context = {
        'image': instance.image,
        'tree': instance.tree,
        'result': result,
    }
    return render(request, 'recognition/recognition.html', context)


class ShowAll(generic.ListView):
    template_name = 'recognition/all_pic.html'
    context_object_name = 'all_images'
    paginate_by = 8

    def get_queryset(self):
        return Recognition.objects.all().order_by('-id')


"""class ShowTrees(generic.ListView):
    template_name = 'recognition/all_tree.html'
    context_object_name = 'all_tree'
    paginate_by = 8

    def get_queryset(self):
        return Tree.objects.all().order_by('id')"""

def show_trees(request):
    all_tree = Tree.objects.all().order_by('id')
    maple = Recognition.objects.filter(tree=all_tree[0]).count()
    birch = Recognition.objects.filter(tree=all_tree[1]).count()
    willow = Recognition.objects.filter(tree=all_tree[2]).count()
    context = {
        'all_tree': all_tree,
        'maple': maple,
        'birch': birch,
        'willow': willow,
    }
    return render(request, 'recognition/all_tree.html', context)


"""class TheTree(generic.DetailView):
    template_name = 'recognition/tree_detail.html'
    model = Tree
    pk_url_kwarg = 'id'

    def lol2(self):
        return self.kwargs['id']

    #lol = Recognition.objects.filter(tree=Tree.objects.filter(id=lol2))"""


def the_tree(request, id=None):
    instance = get_object_or_404(Tree, id=id)
    images = Recognition.objects.filter(tree=instance)
    context = {
        'tree': instance,
        'images': images,
    }
    return render(request, 'recognition/tree_detail.html', context)





class PersonalAcc(generic.ListView):
    template_name = 'recognition/personal_account.html'
    context_object_name = 'account_img'
    paginate_by = 8

    def get_queryset(self):
        return Recognition.objects.filter(user=self.request.user)


class SearchList(generic.ListView):
    template_name = 'recognition/search_res.html'
    context_object_name = 'res'
    paginate_by = 8

    def get_queryset(self):
        res = Recognition.objects.all()
        query = self.request.GET.get('q')
        if query:
            query_list = query.split()
            res = res.filter(
                reduce(operator.and_,
                       (Q(tree__title__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                       (Q(user__username__icontains=q) for q in query_list))
            )
        return res

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'index.css'%}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" style="{% block logo %} {% endblock %}" href="{% url 'recognition:index' %}">Leaves Recognition</a>
        </div>
        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ui class="nav navbar-nav">
                <li class="{% block all_pic %}{% endblock %}">
                    <a href="{% url 'recognition:all_pic' %}">
                        <span class="glyphicon glyphicon-list-alt"aria-hidden="true"></span>&nbsp;
                        Pictures
                    </a>
                </li>
            </ui>
            <ui class="nav navbar-nav">
                <li class="{% block all_tree %}{% endblock %}">
                    <a href="{% url 'recognition:trees' %}">
                        <span class="glyphicon glyphicon-list-alt"aria-hidden="true"></span>&nbsp;
                        Trees
                    </a>
                </li>
            </ui>
            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'recognition:search' %}" accept-charset="utf-8">
                <div class="input-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}" placeholder="Search">
                    <div class="input-group-btn">
                        <button class="btn btn-default" type="submit">
                            <i class="glyphicon glyphicon-search"></i>
                         </button>
                    </div>
                </div>
            </form>
            <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated %}
                <li class="{% block personal_acc %}{% endblock %}">
                    <a href="{% url 'recognition:personal_acc' %}">
                        Account ({{user}})
                    </a>
                </li>
                <li>
                    <a href="{% url 'auth_logout' %}">
                        <span class="glyphicon  glyphicon-off" aria-hidden="true"></span>&nbsp;
                        Logout
                    </a>
                </li>
                {% else %}
                <li class="{% block login_active %} {% endblock %}">
                    <a href="{% url 'auth_login' %}">
                        <span class="glyphicon  glyphicon-log-in" aria-hidden="true"></span>&nbsp;
                        Login
                    </a>
                </li>
                <li class="{% block register_active %} {% endblock %}">
                    <a href="{% url 'registration_register' %}">
                        <span class="glyphicon  glyphicon-user" aria-hidden="true"></span>&nbsp;
                        Register
                    </a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

templates/recognition/all_pic.html
{% extends 'base.html' %}
{% block title %}All recognized pictures{% endblock %}
{% block all_pic %}active{% endblock %}
{% block body %}
<div class="container" style="margin-top:20px;">
    <div class="row" >
        {% for image in all_images %}
        <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
            <div class="thumbnail">
                <a href="{% url 'recognition:recognition' id=image.id %}">
                    <img src="{{image.image.url}}" class="img-responsive img-show" style="display: block;object-fit: cover;height: 250px;max-width: 100%;">
                    <div class="caption">
                        <h5>Tree: {{image.tree}}</h5>
                        <h5>Created at: {{image.created_at}}</h5>
                        <h5>Modified at: {{image.modified_at}}</h5>
                        <h5>User: None</h5>
                    </div>
                </a>
            </div>
        </div>
        {% endfor %}
    </div>

    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" style="text-align:center;">
            <div class="pagination">
                <span class="page-links">
                    {% if page_obj.has_previous %}
                        <a href="/all_pictures?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}
                    <span class="page-current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>
                    {% if page_obj.has_next %}
                        <a href="/all_pictures?page={{ page_obj.next_page_number }}">next</a>
                    {% endif %}
                </span>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/recognition/all_tree.html
{% extends 'base.html' %}
{% block title %}All Trees{% endblock %}
{% block all_tree %}active{% endblock %}
{% block body %}
<div class="container" style="margin-top:20px;">
    <div class="row good_row" >
        <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
            <div class="thumbnail">
                <div class="caption">
                    <h5 style="text-align:center">Count of recognized pictures:</h5>
                    <canvas id="myDoughnutChart" style="max-width:100%"></canvas>
                    <script>
                        var ctx = document.getElementById("myDoughnutChart");
                        var data = {
                            labels: [
                                "{{all_tree.0.title|title}}",
                                "{{all_tree.1.title|title}}",
                                "{{all_tree.2.title|title}}"
                            ],
                            datasets: [
                                {
                                    label: "result",
                                    data: [{{maple}}, {{birch}}, {{willow}}],
                                    backgroundColor: [
                                        "#FF6384",
                                        "#36A2EB",
                                        "#AEFF60"
                                    ],
                                    hoverBackgroundColor: [
                                        "#FF6384",
                                        "#36A2EB"
                                    ]
                                }]
                        };
                        var myBarChart = new Chart(ctx, {
                            type: 'horizontalBar',
                            data: data,
                            options: {
                                legend: { display: false },
                                scales: {
                                    xAxes: [{
                                        ticks: {
                                            min: 0 // Edit the value according to what you need
                                        }
                                    }],
                                    yAxes: [{
                                        stacked: true
                                    }]
                                }
                            }
                        });
                    </script>
                </div>
            </div>
        </div>
        {% for tree in all_tree %}
        <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
            <div class="thumbnail">
                <a href="{% url 'recognition:the_tree' id=tree.id %}">
                    <img src="{{tree.image.url}}" class="img-responsive img-show" style="display: block;object-fit: cover;height: 250px;max-width: 100%;">
                    <div class="caption">
                        <h5 style="text-align:center"><b>{{tree.title|upper}}</b></h5>
                    </div>
                </a>
            </div>
        </div>
        {% endfor %}
    </div>

    <div class="row good_row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" style="text-align:center;">
            <div class="pagination">
                <span class="page-links">
                    {% if page_obj.has_previous %}
                        <a href="/all_trees?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}
                    <span class="page-current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>
                    {% if page_obj.has_next %}
                        <a href="/all_trees?page={{ page_obj.next_page_number }}">next</a>
                    {% endif %}
                </span>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/recognition/index.html
{% extends 'base.html' %}
{% block title %}Leaves Recognition{% endblock %}
{% block logo %}background-color:#000000; color:#ffffff{% endblock %}
{% block body %}
<section class="jumbotron">
    <div class="container">
        <div class="row" align="center">
            <figure class="col-sm-12">
                <figure class="col-sm-6 col-sm-offset-5 black">
                    <br>
                    <form action="{% url 'recognition:index' %}" method="post" enctype="multipart/form-data" class="choose">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <p>Select an Image:</p>
                        <label for = "id_image" class="vis btn btn-default">Browse</label>
                        <input class="upload" id="uploadFile" placeholder="Choose .jpeg File" disabled="disabled"/>
                        <br>
                        <input type="submit" value="Submit" class="btn btn-success" style="bottom:15px;margin-top: 20px;"/>
                    </form >
                    <br>
                </figure>
            </figure>
        </div>
    </div>
</section>
<script>document.getElementById("id_image").onchange = function () {
                            document.getElementById("uploadFile").value = this.value;
                        };</script>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <div style="background-color:white">
                lol
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/recognition/personal_account.html
{% extends 'base.html' %}
{% block title %}{{request.user}}{% endblock %}
{% block personal_acc %}active{% endblock %}
{% block body %}
<div class="container" style="margin-top:20px;">
    <div class="row good_row" >
        <div class="col-lg-12">
            <div class="thumbnail">
                <h5 style="text-align: center"><b>username:</b> {{account_img.0.user}},
                    <b>email:</b> {{account_img.0.user.email}},
                    <b>date joined:</b> {{account_img.0.user.date_joined}}</h5>
            </div>
        </div>
    </div>
    <div class="row good_row" >
        {% for image in account_img %}
        <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
            <div class="thumbnail">
                <a href="{% url 'recognition:recognition' id=image.id %}">
                    <img src="{{image.image.url}}" class="img-responsive img-show" style="display: block;object-fit: cover;height: 250px;max-width: 100%;">
                    <div class="caption">
                        <h5>Tree: {{image.tree}}</h5>
                        <h5>User: {{image.user}}</h5>
                        <h5>Created at: {{image.created_at}}</h5>
                        <h5>Modified at: {{image.modified_at}}</h5>
                    </div>
                </a>
            </div>
        </div>
        {% endfor %}
    </div>

    <div class="row good_row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" style="text-align:center;">
            <div class="pagination">
                <span class="page-links">
                    {% if page_obj.has_previous %}
                        <a href="/account?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}
                    <span class="page-current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>
                    {% if page_obj.has_next %}
                        <a href="/account?page={{ page_obj.next_page_number }}">next</a>
                    {% endif %}
                </span>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/recognition/recognition.html
{% extends 'base.html' %}
{% block title %}Leaves Recognition{% endblock %}
{% block body %}
<section class="container col-centered" style="margin-top:20px;">
    <div class="row col-centered good_row" align="center">
        <figure class="col-md-5  col-centered">
            <div class="thumbnail">
            <div class="caption">
                <p>Result:</p>
                <p>{{result.0|title}} ~ {% widthratio result.1 1 100 %}%</p>
                <canvas id="myDoughnutChart" style="max-width:100%"></canvas>
                <script>
                var ctx = document.getElementById("myDoughnutChart");
                var data = {
                    labels: [
                        "{{result.0|title}}",
                        "{{result.2|title}}",
                        "{{result.4|title}}"
                    ],
                    datasets: [
                        {
                            data: [{{result.1}}*100, {{result.3}}*100, {{result.5}}*100],
                            backgroundColor: [
                                "#FF6384",
                                "#36A2EB",
                                "#AEFF60"
                            ],
                            hoverBackgroundColor: [
                                "#FF6384",
                                "#36A2EB"
                            ]
                        }]
                };
                    var myDoughnutChart = new Chart(ctx, {
                        type: 'doughnut',
                        data: data,
                        options: {
                            responsive: false
                        }
                    });
                </script>
            </div>
                </div>
        </figure>

        <figure class="col-md-7  col-centered" style="margin-right:0px;">
            <div class="thumbnail">
            <div class="caption">
                <p>Your Image:</p>
                <img src='{{image.url}}' style="display: block;object-fit: cover;height: 329px;max-width: 100%;"/>
            </div>
                </div>
        </figure>
    </div>
    <div class="row good_row">
        <div class="col-lg-12">
            <div class="thumbnail">
                <div style="margin:20px; text-align: justify;text-indent: 1.5em;line-height: 1.5">
                    <p style="text-align: center;"><b>{{tree.title|upper}}</b></p>
                    <p style="margin-bottom: 0em;">
                        <img src="{{tree.image.url}}" align="left" style="margin: 0px 20px 10px 0px;height: 329px;max-width: 100%;"/>
                        {{tree.description|safe}}
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/recognition/search_res.html
{% extends 'base.html' %}
{% block title %}Result{% endblock %}
{% block body %}
{% if res %}
    <div class="container" style="margin-top:20px;">
        <div class="row good_row" >
            {% for image in res %}
            <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
                <div class="thumbnail">
                    <a href="{% url 'recognition:recognition' id=image.id %}">
                        <img src="{{image.image.url}}" class="img-responsive img-show" style="display: block;object-fit: cover;height: 250px;max-width: 100%;">
                        <div class="caption">
                            <h5><b>Tree: {{image.tree}}</b></h5>
                            <h5><b>User: {{image.user}}</b></h5>
                            <h5>Created at: {{image.created_at}}</h5>
                            <h5>Modified at: {{image.modified_at}}</h5>
                        </div>
                    </a>
                </div>
            </div>
            {% endfor %}
        </div>

        <div class="row good_row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" style="text-align:center;">
                <div class="pagination">
                    <span class="page-links">
                        {% if page_obj.has_previous %}
                            <a href="{% if request.GET.q %}?q={{ request.GET.q }}{% endif %}&page={{ page_obj.previous_page_number }}">previous</a>
                        {% endif %}
                        <span class="page-current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                        </span>
                        {% if page_obj.has_next %}
                            <a href="{% if request.GET.q %}?q={{ request.GET.q }}{% endif %}&page={{ page_obj.next_page_number }}">next</a>
                        {% endif %}
                    </span>
                </div>
            </div>
        </div>
    </div>
{% else %}
    <h3 style="text-align:center;">No Results found</h3>
{% endif %}
{% endblock %}

templates/recognition/tree_detail.html
{% extends 'base.html' %}
{% block title %}{{tree.title}}{% endblock %}
{% block body %}
<section class="container col-centered" style="margin-top:20px;">
    <div class="row good_row">
        <div class="col-lg-12">
            <div class="thumbnail">
                <div style="margin:20px; text-align: justify;text-indent: 1.5em;line-height: 1.5">
                    <p style="text-align: center;"><b>{{tree.title|upper}}</b></p>
                    <p style="text-align: center;">The count of recognized images: {{ images.count }}</p>
                    <p style="margin-bottom: 0em;">
                        <img src="{{tree.image.url}}" align="left" style="margin: 0px 20px 10px 0px;height: 329px;max-width: 100%;"/>
                        {{tree.description|safe}}
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}